### ISSUE TITLE
Dependency conflicts in C# project

### ISSUE THREAD

**Issue by V0d01ey** [dotnet-websharper/jqueryui#10]
Adding package WebSharper.JQueryUI to C# WebSharper project results in dependency conflicts: "Found conflicts between different versions of the same dependent assembly."
Trying to resolve them with <assemblyBinding> don't help as the project get stuck with following error:

> 1>C:\Users\prime\source\repos\ClientServer5\ClientServer5\Server.cs(42,48,42,55): error CS0433: The type 'Content' exists in both 'WebSharper.Html.Server, Version=4.2.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71' and 'WebSharper.Sitelets, Version=4.2.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'

**Comment by V0d01ey** [comment]
Can someone give some project that can be used for an example to change the project jqueryui for a new release?

**Comment by AlexPeret** [comment]
looks like your project is mixing different versions of WebSharper libs. Double check each library looking for the differences in version. If one is using v4.2 and another v4.3, WebSharper compiler will throw an exception.

Regarding to your second comment, I'm not sure if it is required. Just updating the versions using Nuget will be enough.

**Comment by V0d01ey** [comment]
@AlexPeret , don't your C#-project face this problem?

**Comment by Tarmil** [comment]
Hi, this issue has been fixed in WebSharper.Html 4.5 (as reported [here](https://github.com/dotnet-websharper/html/issues/5)).

**Comment by V0d01ey** [comment]
@Tarmil , is it possible to get ```WebSharper.Html.Client.Element``` from ```WebSharper.JavaScript.Dom``` ?

**Comment by Tarmil** [comment]
Hmm, I don't think so. What's your use case?

**Comment by V0d01ey** [comment]
If project is using everywhere Elt objects then this JQueryUI lib will be useful only if it get rid of ```WebSharper.Html``` dependency. Is it so?
For example to show in Dialog widget some complicated html one shouldn't use WebSharper.UI classes (aka Elt) to generate them.
