### ISSUE TITLE
jqueryui project won't build locally - unauthorized exception

### ISSUE THREAD

**Issue by AlexPeret** [dotnet-websharper/jqueryui#11]
hi!

I'm trying to build dotnet-websharper/jqueryui locally, but I'm facing an **unauthorized** exception after running the **build.sh** script from Git Bash:

```
...
Source 'https://nuget.intellifactory.com/nuget' exception: System.Exception: error ---> System.Exception: Could not retrieve data from 'https://nuget.intellifactory.com/nuget/Packages?$filter=(tolower(Id) eq 'websharper') and (Version eq '4.3.0.274')' ---> Paket.Utils+RequestFailedException: Request to 'https://nuget.intellifactory.com/nuget/Packages?$filter=(tolower(Id) eq 'websharper') and (Version eq '4.3.0.274')' failed with: 'Unauthorized'
...
Something failed in GetPackageDetails, trying again with force: Couldn't get package details for package WebSharper.FSharp 4.3.0.274 on https://nuget.intellifactory.com/nuget.
...
```

Looks like it is regarded to the lack of privilege to access a paket script somewhere.

What do you guys advice?

Thanks,
Alex

**Comment by V0d01ey** [comment]
You should remove "prerelease" version in paket.dependencies file to build without usage of private repositories. 
Then you should call update command: `.paket\paket update`
After that `build.cmd` will work.

**Comment by AlexPeret** [comment]
thank you! that solved the problem.
